"""empty message

Revision ID: 175a3fbf7b6c
Revises: 73fd1488c315
Create Date: 2019-11-04 12:30:13.534747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175a3fbf7b6c'
down_revision = '73fd1488c315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_link', sa.String(length=500), nullable=False))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###
